# Generated by Django 3.2.7 on 2021-11-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-message_date',), 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('general', 'General Questions'), ('product_information', 'Product Information'), ('order_status', 'Order Status'), ('shipping_delivery', 'Shipping and Delivery'), ('bulk_purchasing', 'Wholesale Purchasing')], default='general', max_length=254),
        ),
    ]
