# Generated by Django 3.2.7 on 2021-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211013_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
